### ISSUE TITLE
secondary uids are not recognized

### ISSUE THREAD

**Issue by pravi** [whiteout-io/browserbox#47]
I tried chrome app with my key 0x4512c22a. But could not complete setup because of uid mismatch. Secret key was exported using gpg --export-secret-key --armour

**Comment by asutherland** [comment]
This seems like it's intended to be a bug/support request against a higher level in the whiteout.io app stack?

**Comment by felixhammerl** [comment]
browserbox is the IMAP layer, no pgp going on here. will close this ticket
