### ISSUE TITLE
Any work planned for "advanced" gmail login

### ISSUE THREAD

**Issue by wimvanhouts** [whiteout-io/browserbox#61]
Hi, 

do you have an example on how to login into a Gmail IMAP mailbox with default "advanced" authentication enabled? Or is this currently not supported, and in this case, is there any work done to do this in the future? 
Otherwise this is a really nice piece of code !

Kr, 

Wim

**Comment by andris9** [comment]
If by "advanced" you mean google 2-factor login then this is already supported, you either need to generate and use an application specific password for BrowserBox or use OAuth2.

**Comment by wimvanhouts** [comment]
via via indeed got to xoauth2 npm package to generate access token. Trying to get that to work now. Thx for the swift response...

**Comment by andris9** [comment]
Ok, great. Just remember that the correct OAuth2 scope for Gmail is "https://mail.google.com/".
