### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by polaski** [whiteout-io/browserbox#65]
Hi thanks for creating this, i have been trying to figure out how to use this client side only (no node, but purely in browser) but couldn't. I looked at the example code and tried changing it around but still couldn't make it work.

I thought about posting on Stackoverflow but saw that someone else had asked the same question and got no answer so decided to ask here.

Could you give me a pointer on how to get started? Thank you!

**Comment by asutherland** [comment]
You need a tcp-socket implementation, which is not available in browser contexts by default.  So you either need to use existing web tech to proxy to something that can do TCP for you or use a combination of shims and permissions in an appropriate browser context.  See https://github.com/whiteout-io/tcp-socket for more info in general.

If you're using Firefox/Gecko, see https://github.com/mozilla-b2g/gaia/blob/master/apps/email/README.md for info on enabling mozTCPSocket.  Alternately, use the Firefox extension at https://github.com/mykmelez/tcpsocketpup. (Click on "Latest release", then click on the XPI download. A door-hanger thing should happen to let you allow the installation of the extension, etc. Do the danger dance and get that extension installed, then click the icon it added when you're browsing at the origin you want to enable the privilege for.)

**Comment by felixhammerl** [comment]
i assume this issue can be closed for now?
