### ISSUE TITLE
selectMailbox not working

### ISSUE THREAD

**Issue by marcus433** [whiteout-io/browserbox#66]
For some reason selectMailbox returns this error every so often. It may be nothing, just sharing incase it is an actual issue.
![screen shot 2015-07-22 at 12 15 39 pm](https://cloud.githubusercontent.com/assets/4731718/8834842/a3d59366-306b-11e5-84cf-539f5899855a.png)

**Comment by asutherland** [comment]
This seems like a server issue, possibly involving a limited-capability proxy that only understands enough IMAP to perform login and then hand-off the connection.  For example, fastmail uses an nginx proxy that doesn't understand ID and sometimes doesn't hand-off to the real Cyrus implementation before browserbox issues its ID command.

What server are you talking to when this happens?

**Comment by marcus433** [comment]
Im talking to imap.mail.yahoo.com. I have 2 instances of BrowserBox, one connecting to imap.mail.yahoo.com, the other connecting to imap.gmail.com.

**Comment by marcus433** [comment]
Each instance of browserbox is encapsulated by its own ImapClient instance. When running them alone everything seems to be fine, but when running both ImapClients in parallel, that seems to be when the issue occurs most often.

**Comment by asutherland** [comment]
Ah, yeah, I've seen various cases where Yahoo won't let me SELECT/EXAMINE the inbox temporarily.  I could've sworn those manifested as NO, but I didn't keep great notes about what specifically I saw.  It's also possible they've changed from NO to BAD based on how clients respond to that scenario.

And in these cases I don't think there was anything special happening like concurrent access by another client via POP3 or even IMAP.  I think Yahoo just has a weird server implementation.

**Comment by marcus433** [comment]
Interesting, what's weird is that this error occurs for both yahoo and gmail which is why I was led to believe it may relate to concurrent connections, as Gmail has never had this error on it's own.

**Comment by asutherland** [comment]
Whoops, I went into this bug biased by the server errors I've experienced; I should have looked at the screenshot more clearly.  The server is claiming you actually sent "xg13mb..." as the command.  Which suggests that indeed the two instances are interacting somehow.

For FxOS email we use browserbox with native TCPSocket without problems like this AFAICT, so I would suspect either whatever you're using for TCPSocket purposes or some accidental object reuse.  (Failure to "new" somewhere?)

**Comment by marcus433** [comment]
Thank you for the replies, really appreciate it! I am using the native node TCPSocket and am using `new` on an instance of https://github.com/whiteout-io/imap-client . From what I can tell whiteout-io/imap-client handles all `new` instances correctly. Not quite sure what I could be doing wrong as Im essentially just doing var instance1 = new ImapClient();var instance2 = new ImapClient();. Hopefully this is just a case of an error on my end. Ill investigate further, if it isn't on my end Ill post here so it can be fixed :)

**Comment by andris9** [comment]
You should check what is actually written to the socket as the logged information is a derivation from the input and not actual sent bytes

**Comment by marcus433** [comment]
Thank you, I will check that out. Also, upon investigation of browserbox-imap I noticed the TLSSocket-Shim is initiated like this this._TCPSocket = TCPSocket;. May this be why concurrent connections are failing? e.g. a setup for new TCPSocket()

**Comment by marcus433** [comment]
It is now returning a new error even though nothing has been changed.
![screen shot 2015-07-22 at 1 56 20 pm](https://cloud.githubusercontent.com/assets/4731718/8837157/cc21b21a-3079-11e5-900a-42b7a602ae56.png)

**Comment by marcus433** [comment]
Found the issue. It appears running a selectMailbox too early or running it at the same time as login results in BrowserBox crashing and these errors then ensue. Thank you for all of your guys' help!
