### ISSUE TITLE
Message parser

### ISSUE THREAD

**Issue by benmer47** [whiteout-io/browserbox#70]
Thank you for this amazing module :) 

Juste a short question. Is there another module to parse the return value of the function listMessages() ?
I just found your other module "mailparser" but i don' get behind how to use ist :D. 

Kind Regards

**Comment by felixhammerl** [comment]
you can use [mailreader](https://github.com/whiteout-io/mailreader) or just mimic its behavior to see how to use mailparser, see the [source](https://github.com/whiteout-io/mailreader/blob/master/src/mailreader-parser.js)
