### ISSUE TITLE
Logging verbosity

### ISSUE THREAD

**Issue by qqilihq** [whiteout-io/browserbox#71]
Hi there,

thanks for that great library! I'm currently trying to disable the very verbose debug logging. An older ticket suggested setting the log level via axe, so I tried the following:

    var axe = require('axe-logger');
    axe.logLevel = axe.ERROR;

Which I placed at the very top of my script. However, I still receive the very verbose debug logging. I'm running in a node.js environment. Any hints appreciated!

**Comment by edudutra** [comment]
Same here.

Any hints?

Tks...

**Comment by felixhammerl** [comment]
uhm ... that's weird. no idea why it doesn't affect logging verbosity. for me, this always did the trick.

another idea: axe was created in about 5 minutes, because i couldn't find a logging tool for all platforms. ideas? we might get rid of it as well, if there's no immediate benefit anymore...

**Comment by qqilihq** [comment]
Hey Felix,

thank you for your message. For me, the issue is not extremely urgent. However, during setup, the logging was very helpful, so I would suggest having some hook, which allows supplying an arbitrary log method would be most flexible. Something like this:

    var client = new BrowserBox(…);
    client.onlog = function(message) {
        // use user's preferred way of logging, or supply an empty method to suppress logging
        console.log('logging from BrowserBox', message);
    };

**Comment by felixhammerl** [comment]
you can write your own appender, as i did with the default console appender: https://github.com/whiteout-io/axe/blob/master/axe.js#L25-L45

```
// appenders
axe.defaultAppender // logs to the console

var appender = {
    log: function(level, date, component, message) {
        // do stuff
    }
}    
axe.addAppender(appender);
axe.removeAppender(appender);
```

**Comment by qqilihq** [comment]
Unfortunately, this does not seem to have any effect. Used the following axe setup, which should completely suppress warning from my understanding:

    var axe = require('axe-logger');
    axe.removeAppender(axe.defaultAppender);
    axe.addAppender({log: function(level, date, component, message) {
	// do nothing
    }});

Yet I receive all the logging.

**Comment by felixhammerl** [comment]
will be obsoleted by #72

**Comment by edudutra** [comment]
After I updated node to v 5.0.0 it's working.

**Comment by nrutman** [comment]
So how do I disable all of the debug logging in v2.0.3? I'm using that because v3 doesn't play well with Node (see https://github.com/emailjs/emailjs-imap-client/issues/165).

It looks like 2.0.3 works fine…I'm just trying to get rid of the debug statements.

**Comment by felixhammerl** [comment]
Check [the integration test of v2](https://github.com/emailjs/emailjs-imap-client/blob/25bbf7bfb554ffe9b14c5a6fe65f010bc76cd231/test/integration/emailjs-imap-client-test.js#L94).

however try v3 again, bug was fixed.
